# Generated by Django 4.1.5 on 2023-01-25 15:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('id_ps', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('need_scale', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('study_supplies_accept', models.BooleanField(default=False)),
                ('study_supplies_needed_type', models.CharField(blank=True, choices=[('stationery', 'stationery'), ('g1', 'g1'), ('g2', 'g2'), ('g3', 'g3'), ('g4', 'g4'), ('g5', 'g5'), ('g6', 'g6'), ('g7', 'g7'), ('g8', 'g8'), ('g9', 'g9'), ('g10', 'g10'), ('g11_sen', 'g11_sen'), ('g11_lit', 'g11_lit'), ('g12_sen', 'g12_sen'), ('g12_lit', 'g12_lit')], max_length=30, null=True)),
                ('clothes_needed_type', models.CharField(blank=True, choices=[('babys', 'babys'), ('girls', 'girls'), ('boys', 'boys'), ('men', 'men'), ('womon', 'womon')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('mosque', 'mosque'), ('Charity', 'Charity'), ('other', 'other')], max_length=30)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'food'), ('clothes', 'clothes'), ('study_supplies', 'study_supplies')], max_length=30)),
                ('study_supplies_type', models.CharField(blank=True, choices=[('stationery', 'stationery'), ('g1', 'g1'), ('g2', 'g2'), ('g3', 'g3'), ('g4', 'g4'), ('g5', 'g5'), ('g6', 'g6'), ('g7', 'g7'), ('g8', 'g8'), ('g9', 'g9'), ('g10', 'g10'), ('g11_sen', 'g11_sen'), ('g11_lit', 'g11_lit'), ('g12_sen', 'g12_sen'), ('g12_lit', 'g12_lit')], max_length=30, null=True)),
                ('clothes_type', models.CharField(blank=True, choices=[('babys', 'babys'), ('girls', 'girls'), ('boys', 'boys'), ('men', 'men'), ('womon', 'womon')], max_length=30, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('notes', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_point_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.delivery_point')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Charity', 'Charity'), ('Governmental_institution', 'Governmental_institution'), ('other', 'other')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_ai', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.beneficiary')),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.donation')),
                ('message_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receipt_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.receipt'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='registrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.registrar'),
        ),
    ]
