# Generated by Django 4.1.5 on 2023-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delivery_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='clothes_accept',
            field=models.BooleanField(default=True),
        ),
    ]
