# Generated by Django 4.1.5 on 2023-02-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_beneficiary_clothes_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('clothes', 'clothes'), ('study_supplies', 'study_supplies')], max_length=30),
        ),
        migrations.CreateModel(
            name='item_desire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_scale', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('beneficiary_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.beneficiary')),
                ('item_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.item')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='item_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.item'),
        ),
    ]
