# Generated by Django 4.1.5 on 2023-02-24 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delivery_point_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_desire',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_desire',
            name='desire_scale',
            field=models.IntegerField(choices=[(0, 0), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
