# Generated by Django 4.1.5 on 2023-02-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bio',
            field=models.CharField(default='s', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
