# Generated by Django 4.1.5 on 2023-02-24 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_donation_bio_alter_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_point_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.delivery_point')),
            ],
        ),
    ]
