# Generated by Django 4.1.5 on 2023-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_item_demand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='by_ai',
            new_name='recipient',
        ),
    ]
