# Generated by Django 4.1.5 on 2023-02-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_by_ai_receipt_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pieces_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
