# Generated by Django 4.1.5 on 2023-02-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_donation_pieces_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='recipient',
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient',
            field=models.BooleanField(default=False),
        ),
    ]
