# Generated by Django 4.1.5 on 2023-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_receipt_recipient_donation_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('readed', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='clothes_needed_type',
            field=models.CharField(blank=True, choices=[('babys', 'babys'), ('child', 'child'), ('girls', 'girls'), ('boys', 'boys'), ('men', 'men'), ('womon', 'womon')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='clothes_type',
            field=models.CharField(blank=True, choices=[('babys', 'babys'), ('child', 'child'), ('girls', 'girls'), ('boys', 'boys'), ('men', 'men'), ('womon', 'womon')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='img',
            field=models.ImageField(upload_to='donation/'),
        ),
    ]
