# Generated by Django 4.1.5 on 2023-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_user_message_alter_beneficiary_clothes_needed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='phone_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
