# Generated by Django 4.1.5 on 2023-03-08 18:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_user_message_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_point',
            name='user_phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='clothes_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.item'),
        ),
    ]
